Repository AY2122S1-CS2113T-T12-3/tp, pull requests merged in 2021-10, with the labels that each got.

#64 Add data saving class (DataManager)
  StonksXD_Data.csv
  src/main/java/seedu/duke/Parser.java
  src/main/java/seedu/duke/StonksXD.java
  src/main/java/seedu/entry/Expense.java
  src/main/java/seedu/entry/Income.java
  src/main/java/seedu/utility/DataManager.java
  src/main/java/seedu/utility/Messages.java
  src/test/java/seedu/duke/DataManagerTest.java
  src/test/java/seedu/duke/ParserTest.java
  src/test/java/seedu/duke/UiTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/StonksXD_Data.csv
  text-ui-test/runtest.sh
Labels: priority.High

#79 Integrate StonksGraph with rest of code
  StonksXD_Data.csv
  src/main/java/seedu/commands/ShowGraphCommand.java
  src/main/java/seedu/utility/Parser.java
  src/main/java/seedu/utility/StonksGraph.java
  src/main/java/seedu/utility/Ui.java
Labels: priority.High

#80 added UI image to ignore
  .gitignore
  docs/DeveloperGuide.md
  src/main/java/seedu/utility/StonksGraph.java
  src/main/java/seedu/utility/Ui.java
Labels: priority.Medium

#91 Minor changes cleaningup
  src/main/java/seedu/commands/FindCommand.java
  src/main/java/seedu/utility/CommandFormat.java
  src/main/java/seedu/utility/DataManager.java
  src/main/java/seedu/utility/FinancialTracker.java
  src/main/java/seedu/utility/Messages.java
  src/main/java/seedu/utility/Parser.java
  src/main/java/seedu/utility/StonksGraph.java
  src/main/java/seedu/utility/Ui.java
Labels: priority.Medium

#92 More tests for Command Class
  src/test/java/seedu/duke/CommandTest.java
Labels: priority.Medium

#99 Update data saving class to save budget settings
  StonksXD_Data.csv
  StonksXD_Entries.csv
  src/main/java/seedu/duke/StonksXD.java
  src/main/java/seedu/utility/DataManager.java
  src/main/java/seedu/utility/Messages.java
  src/main/java/seedu/utility/Parser.java
  src/test/java/seedu/duke/DataManagerTest.java
  text-ui-test/EXPECTED.TXT
  text-ui-test/StonksXD_Data.csv
  text-ui-test/StonksXD_Entries.csv
  text-ui-test/runtest.sh
Labels: type.Task, priority.High

#160 Fix Table of Contents link in UG and allow users to manually add date for entries
  docs/UserGuide.md
  src/main/java/seedu/utility/Parser.java
  src/test/java/seedu/duke/ParserTest.java
  src/test/java/seedu/duke/TotalExpenseBetweenCommandTest.java
  src/test/java/seedu/duke/TotalIncomeBetweenCommandTest.java
Labels: priority.Medium

#195 Fixed invalid date range for btw_in and btw_ex commands - Ped bugs
  StonksXD_Entries.csv
  docs/UserGuide.md
  src/main/java/seedu/commands/expense/AddExpenseCommand.java
  src/main/java/seedu/commands/income/AddIncomeCommand.java
  src/main/java/seedu/duke/StonksXD.java
  src/main/java/seedu/exceptions/DuplicateExpenseException.java
  src/main/java/seedu/exceptions/DuplicateIncomeException.java
  src/main/java/seedu/utility/FinancialTracker.java
  src/main/java/seedu/utility/Messages.java
  src/main/java/seedu/utility/Parser.java
  src/main/java/seedu/utility/datetools/DateOperator.java
  src/test/java/seedu/duke/BalanceCommandTest.java
  src/test/java/seedu/duke/BudgetManagerTest.java
  src/test/java/seedu/duke/DataManagerTest.java
  src/test/java/seedu/duke/FinancialTrackerTest.java
  src/test/java/seedu/duke/ParserTest.java
  src/test/java/seedu/duke/TotalExpenseBetweenCommandTest.java
  src/test/java/seedu/duke/TotalIncomeBetweenCommandTest.java
  src/test/java/seedu/duke/UiTest.java
Labels: priority.Medium

#196 [PED] Fix bug where NaN and Infinity are possible double input
  StonksXD_Entries.csv
  StonksXD_Settings.csv
  src/main/java/seedu/utility/Parser.java
Labels: priority.Medium

#197 Update User guide
  docs/UserGuide.md
Labels: priority.Medium, severity.Medium
