Repository AY2122S1-CS2113T-T12-3/tp, pull requests merged in 2021-11, with the labels that each got.

#200 Removed duplicate entries restriction, fix large input amount for expense and income (PED bug)
  docs/UserGuide.md
  src/main/java/seedu/commands/expense/AddExpenseCommand.java
  src/main/java/seedu/commands/income/AddIncomeCommand.java
  src/main/java/seedu/exceptions/DuplicateExpenseException.java
  src/main/java/seedu/exceptions/DuplicateIncomeException.java
  src/main/java/seedu/exceptions/InvalidInputAmountValueException.java
  src/main/java/seedu/utility/FinancialTracker.java
  src/main/java/seedu/utility/Messages.java
  src/main/java/seedu/utility/Parser.java
  src/test/java/seedu/duke/BalanceCommandTest.java
  src/test/java/seedu/duke/BudgetManagerTest.java
  src/test/java/seedu/duke/DataManagerTest.java
  src/test/java/seedu/duke/FinancialTrackerTest.java
  src/test/java/seedu/duke/ParserTest.java
  src/test/java/seedu/duke/TotalExpenseBetweenCommandTest.java
  src/test/java/seedu/duke/TotalIncomeBetweenCommandTest.java
  src/test/java/seedu/duke/UiTest.java
Labels: priority.Medium

#203 Update data saving class to save threshold setting
  StonksXD_Settings.csv
  StonksXD_SettingsBackup.csv
  src/main/java/seedu/exceptions/InvalidThresholdValueException.java
  src/main/java/seedu/utility/DataManager.java
  src/main/java/seedu/utility/Messages.java
  src/main/java/seedu/utility/Parser.java
  src/test/java/seedu/duke/DataManagerTest.java
  src/test/java/seedu/duke/ParserTest.java
Labels: priority.High

#208 Javadoc
  StonksXD_Entries.csv
  StonksXD_EntriesBackup.csv
  docs/UserGuide.md
  docs/team/kyun99.md
  src/main/java/seedu/utility/FinancialTracker.java
Labels: priority.Medium

#211 Update parser class making messages more precise and apt
  StonksXD_Settings.csv
  StonksXD_SettingsBackup.csv
  src/main/java/seedu/utility/Messages.java
  src/main/java/seedu/utility/Parser.java
  src/test/java/seedu/duke/ParserTest.java
Labels: priority.Medium, severity.Medium

#215 Update user guide and small changes to Parser and DataManager
  StonksXD_Budget.csv
  StonksXD_Entries.csv
  StonksXD_EntriesBackup.csv
  StonksXD_Settings.csv
  StonksXD_SettingsBackup.csv
  docs/UserGuide.md
  src/main/java/seedu/utility/DataManager.java
  src/main/java/seedu/utility/Messages.java
  src/main/java/seedu/utility/Parser.java
Labels: priority.High

#217 Updated examples for total_in/ex and btw_in/ex for UG
  docs/UserGuide.md
Labels: type.Enhancement, priority.Medium

#220 Refractor DataManager and Parser
  StonksXD_Entries.csv
  StonksXD_EntriesBackup.csv
  src/main/java/seedu/utility/DataManager.java
  src/main/java/seedu/utility/Messages.java
  src/main/java/seedu/utility/Parser.java
  src/test/java/seedu/duke/DataManagerTest.java
  src/test/java/seedu/duke/ParserTest.java
  text-ui-test/EXPECTED.TXT
Labels: priority.High

#231 Add PPP
  docs/AboutUs.md
  docs/team/anshenglee.md
  docs/team/leeAnSheng.md
Labels: priority.High

#230 Update Developer guide
  docs/DeveloperGuide.md
  src/main/java/seedu/utility/DataManager.java
Labels: priority.High

#236 Update parser for flexible flags order
  src/main/java/seedu/utility/Parser.java
  src/test/java/seedu/duke/ParserTest.java
Labels: priority.Medium

#237 Update developer guide for data saving and parser
  docs/DeveloperGuide.md
  src/main/java/seedu/utility/DataManager.java
Labels: priority.High

#242 Update data saving class and guides
  docs/DeveloperGuide.md
  docs/UserGuide.md
  src/main/java/seedu/utility/DataManager.java
Labels: priority.High

#252 Refractor code
  src/main/java/seedu/exceptions/EntryAmountExceedLimitException.java
  src/main/java/seedu/exceptions/InvalidAmountException.java
  src/main/java/seedu/exceptions/InvalidExpenseAmountException.java
  src/main/java/seedu/exceptions/InvalidIncomeAmountException.java
  src/main/java/seedu/exceptions/InvalidInputAmountValueException.java
  src/main/java/seedu/utility/CommandKeywords.java
  src/main/java/seedu/utility/Parser.java
  src/main/java/seedu/utility/tools/Extractor.java
  src/test/java/seedu/duke/DataManagerTest.java
  src/test/java/seedu/duke/ParserTest.java
Labels: priority.High

#256 Nirmaleshwar PPP
  docs/UserGuide.md
  docs/team/Nirmaleshwar.md
  src/main/java/seedu/commands/ClearAllEntriesCommand.java
  src/main/java/seedu/commands/currency/CurrencyConversionCommand.java
  src/main/java/seedu/commands/currency/CurrencyType.java
  src/main/java/seedu/duke/StonksXD.java
  src/main/java/seedu/entry/Entry.java
  src/main/java/seedu/utility/CurrencyManager.java
  src/main/java/seedu/utility/FinancialTracker.java
  src/main/java/seedu/utility/Parser.java
  src/main/java/seedu/utility/tools/Extractor.java
  src/test/java/seedu/duke/BalanceCommandTest.java
  src/test/java/seedu/duke/BudgetManagerTest.java
  src/test/java/seedu/duke/CommandTest.java
  src/test/java/seedu/duke/DataManagerTest.java
  src/test/java/seedu/duke/FinancialTrackerTest.java
  src/test/java/seedu/duke/ParserTest.java
  src/test/java/seedu/duke/TotalExpenseBetweenCommandTest.java
  src/test/java/seedu/duke/TotalIncomeBetweenCommandTest.java
  src/test/java/seedu/duke/UiTest.java
Labels: priority.High

#263 Refractor code and add javadocs
  src/main/java/seedu/commands/general/FindCommand.java
  src/main/java/seedu/duke/StonksXD.java
  src/main/java/seedu/exceptions/InvalidDescriptionException.java
  src/main/java/seedu/exceptions/InvalidExpenseCategoryException.java
  src/main/java/seedu/exceptions/InvalidExpenseDataFormatException.java
  src/main/java/seedu/exceptions/InvalidIncomeCategoryException.java
  src/main/java/seedu/exceptions/InvalidIncomeDataFormatException.java
  src/main/java/seedu/exceptions/InvalidIndexException.java
  src/main/java/seedu/exceptions/InvalidSettingsDataException.java
  src/main/java/seedu/exceptions/InvalidSettingsDataFormatException.java
  src/main/java/seedu/exceptions/InvalidThresholdValueException.java
  src/main/java/seedu/utility/Messages.java
  src/main/java/seedu/utility/Parser.java
  src/main/java/seedu/utility/Ui.java
  src/main/java/seedu/utility/storage/DataConverter.java
  src/main/java/seedu/utility/storage/DataManager.java
  src/main/java/seedu/utility/tools/DateOperator.java
  src/main/java/seedu/utility/tools/Extractor.java
  src/test/java/seedu/duke/DataConverterTest.java
  src/test/java/seedu/duke/DataManagerTest.java
  src/test/java/seedu/duke/ParserTest.java
Labels: priority.High

#264 Update Developer guide
  docs/DeveloperGuide.md
Labels: priority.High

#265 Add Javadocs
  src/main/java/seedu/entry/Entry.java
  src/main/java/seedu/exceptions/BlankCategoryException.java
  src/main/java/seedu/exceptions/BlankExpenseCategoryException.java
  src/main/java/seedu/exceptions/BlankIncomeCategoryException.java
  src/main/java/seedu/exceptions/EntryAmountExceedLimitException.java
  src/main/java/seedu/exceptions/ExpenseEntryNotFoundException.java
  src/main/java/seedu/exceptions/ExpenseOverflowException.java
  src/main/java/seedu/exceptions/IncomeEntryNotFoundException.java
  src/main/java/seedu/exceptions/IncomeOverflowException.java
  src/main/java/seedu/exceptions/InputException.java
  src/main/java/seedu/exceptions/InvalidAmountException.java
  src/main/java/seedu/utility/FinancialTracker.java
  src/main/java/seedu/utility/tools/DateRange.java
  src/main/java/seedu/utility/tools/Extractor.java
  src/test/java/seedu/duke/CommandTest.java
  src/test/java/seedu/duke/CurrencyManagerStub.java
  src/test/java/seedu/duke/FinancialTrackerTest.java
  src/test/java/seedu/duke/ParserTest.java
Labels: priority.High

#268 Update dg
  docs/FinancialTrackerCD.drawio.png
  src/main/java/seedu/utility/CurrencyManager.java
Labels: priority.High

#274 Update data saving class
  src/main/java/seedu/duke/StonksXD.java
  src/main/java/seedu/utility/storage/DataManager.java
  src/test/java/seedu/duke/DataManagerTest.java
Labels: priority.Medium

#276 Currency Command tests
  src/main/java/seedu/commands/currency/CurrencyType.java
  src/main/java/seedu/utility/CurrencyManager.java
  src/main/java/seedu/utility/Messages.java
  src/main/java/seedu/utility/Parser.java
  src/main/java/seedu/utility/Ui.java
  src/main/java/seedu/utility/tools/Extractor.java
  src/test/java/seedu/duke/CommandTest.java
  src/test/java/seedu/duke/CurrencyManagerStub.java
  src/test/java/seedu/duke/CurrencyManagerTest.java
  src/test/java/seedu/duke/FinancialTrackerTest.java
  src/test/java/seedu/duke/ParserTest.java
  src/test/java/seedu/duke/UiTest.java
Labels: priority.High

#277 Update Developer guide with diagrams
  docs/DataManagerCD.drawio.png
  docs/DeveloperGuide.md
  docs/LoadBudgetsSD.png
  docs/LoadEntriesSD.png
  docs/LoadSettingsSD.png
  docs/SaveEntriesSD.png
  docs/SaveSettingsSD.png
  docs/SavingFeatureSD.drawio.png
  docs/StorageCD.png
Labels: priority.High

#285 Added class diagram for currency component
  docs/CurrencyManagerCD.drawio.png
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/Nirmaleshwar.md
  src/main/java/seedu/utility/Messages.java
  src/main/java/seedu/utility/Ui.java
  src/main/java/seedu/utility/tools/Extractor.java
  text-ui-test/EXPECTED.TXT
Labels: priority.High

#289 Minor changes to spacing in PPP and DG
  docs/DeveloperGuide.md
  docs/team/Nirmaleshwar.md
Labels: priority.High

#290 Update code
  StonksXD_Entries.csv
  src/main/java/seedu/utility/tools/Extractor.java
Labels: priority.High

#291 Final commit
  .github/workflows/gradle.yml
Labels: priority.High

#292 User guide
  docs/DeveloperGuide.md
  docs/UserGuide.md
  docs/team/Nirmaleshwar.md
Labels: priority.High

#294 Update data saving class
  StonksXD_Entries.csv
  src/main/java/seedu/utility/tools/Extractor.java
Labels: type.Bug, priority.High, severity.High

#299 Update PPP
  docs/team/anshenglee.md
Labels: priority.High

#302 Developer guide
  docs/DeveloperGuide.md
Labels: priority.High
